### ISSUE TITLE
cheat sheet tool on www.w3.org/developers/tools

### ISSUE THREAD

**Issue by guibbs** [dontcallmedom/w3c-cheatsheet#9]
Hi @dontcallmedom ,

I was wondering if this tool is still updated or if it's deprecated? 
I would like to add it on https://www.w3.org/developers/tools

**Comment by dontcallmedom** [comment]
I don't think it's deprecated, but I can't say that I've put a lot of efforts in it recently; I leave it to you to determine whether it is an appropriate addition to the developers portal :)
